@urlBase = http://localhost:3000

### Login
# @name login
POST {{urlBase}}/login
Content-Type: application/json

{
  "email": "carlos.souza@example.com",
  "senha": "123"
}

### Buscar todos os filmes
GET {{urlBase}}/filmes
Authorization: Bearer {{login.response.body.$.token}}

### Filtrar filmes
GET {{urlBase}}/filmes?nome=ele
Authorization: Bearer {{login.response.body.$.token}}